name: Automatic increase
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
      with:
        ref: main
        fetch-depth: 0
    - run: |
        latest_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
        MAJOR=$(echo "$latest_tag" | cut -d . -f 1)
        MINOR=$(echo "$latest_tag" | cut -d . -f 2)
        PATCH=$(echo "$latest_tag" | cut -d . -f 3 | cut -d - -f 1)
        timestamp=$(date -u +"%Y%m%d.%H%M")
        pre_version="v${MAJOR}.${MINOR}.${PATCH}-pre-${timestamp}"
        echo "pre_version=$pre_version" >> $GITHUB_ENV
    - run: |
        git tag "${{ env.pre_version }}"
        git push origin "${{ env.pre_version }}"